CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PRICE FLOAT(6,2) NOT NULL,
);

CREATE TABLE CITY(
	ID INT PRIMARY KEY,
	NAME VARCHAR(75) NOT NULL
);

CREATE TABLE NEIGHBORHOOD(
	ID INT PRIMARY KEY,
	NAME VARCHAR(75) NOT NULL,
	CITY INT NOT NULL,

    FOREIGN KEY (CITY)
		REFERENCES CITY(ID)
);

CREATE TABLE ADDRESS(
	ID INT PRIMARY KEY,
    PLACE VARCHAR(75) NOT NULL,
    ZIPCODE VARCHAR(9) NOT NULL,
    NEIGHBORHOOD INT NOT NULL

    FOREIGN KEY (NEIGHBORHOOD)
		REFERENCES NEIGHBORHOOD(ID)
);

CREATE TABLE CLIENT (
    CPF INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    TELEPHONE VARCHAR(14) NOT NULL,
    CELLPHONE VARCHAR(15) NOT NULL,
    NUMBER INT NOT NULL,
    ADDRESS INT NOT NULL,
    INFO VARCHAR(75),

    FOREIGN KEY(ADDRESS)
        REFERENCES ADDRESS(ID)
);

CREATE TABLE STATUS (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(25) NOT NULL
);

CREATE TABLE ORDER (
    ID INT PRIMARY KEY,
    DATE DATETIME NOT NULL,
    STATUS INT NOT NULL,
    CLIENT INT NOT NULL,

    FOREIGN KEY(CLIENT)
        REFERENCES CLIENT(CPF),

    FOREIGN KEY(STATUS)
        REFERENCES STATUS(ID)
);

CREATE TABLE PRODUCT_HISTORY(
    ID INT PRIMARY KEY,
    ID_PRODUCT INT NOT NULL,
    DATA DATETIME NOT NULL,
    PRICE FLOAT(6,2) NOT NULL,

    FOREIGN KEY(ID_PRODUCT)
        REFERENCES PRODUCT(ID)
);

CREATE TABLE PRODUCT_ORDER(
    ID_PRODUCT INT,
    ID_ORDER INT,
    ID_PRODUCT_HISTORY INT NOT NULL,
    AMOUNT INT NOT NULL,

    PRIMARY KEY (ID_PRODUCT, ID_ORDER),

    FOREIGN KEY(ID_PRODUCT)
        REFERENCES PRODUCT(ID),

    FOREIGN KEY(ID_ORDER)
        REFERENCES ORDER(ID),

    FOREIGN KEY(ID_PRODUCT_HISTORY)
        REFERENCES PRODUCT_HISTORY(ID)
);